name: Validate style
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snow-actions/eclint@v1.0.1
      with:
        args: 'check *.d'
